---
title: "Study 1 Pre-Test Results"
subtitle: "Descriptive Data, Correlations, Binomial Regressions, and Post-Hoc Tests"
author: "Jean-Noël George"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    use_bookdown: TRUE
    number_sections: TRUE

---

```{r load-packages, echo=FALSE, include=FALSE}
library("pacman")
p_load(
  "rmdformats", #rmd themes
  "readxl", # load excels
  "writexl", # save to excel
  "tidyverse", # tidy data
  "car", # Levene's and Bartlett's test of non-normal distributions
  "qqplotr", # QQ plots
  "ez", # Test of sphericity
  "dgof", # Kolmogorov-Smirnov test
  "Hmisc", # export anovas etc
  "devtools", # download packages from github
  "emmeans", # post-hoc texts
  "dplyr", # manipulate data
  "purrr", # tidy data (broom)
  "gtsummary", # report regressions
  "finalfit", # visualise regressions
  "ggsignif", # add significance lines to ggplots
  "dlookr", # describe data
  "ppsr", # predictive power scores
  "fastDummies", # dummy-code data
  "flextable", # export to tidy tables
  "sjPlot", # plot regressions
  "report", # report results
  "gtsummary", # report regression tables
  "benelib", #theme_gtsummary_apa
  "easystats", # includes report(), correlations, etc.
  "jtools", # get summ() to summarise and plot regressions
  "performance", # check all assumptions
  "knitr" # for chunk and kable
)


# Set global chunk options
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.align = "center",
  fig.width = 10,
  fig.height = 5
)

# set gtsummary theme as APA
benelib::theme_gtsummary_apa(set_theme = TRUE)

```

```{css, echo=FALSE}



.book .book-body .page-inner section.normal .nav-pills > li > a:hover, .book .book-body .page-inner section.normal .nav-pills > li.active > a, .book .book-body .page-inner section.normal .nav-pills > li.active > a:hover, .book .book-body .page-inner section.normal .nav-pills > li.active > a:focus {
  background-color: #b3d7ff;
  color: #000099;
  border-color:  #000099;
}


.book .book-body .page-inner section.normal a:active, .book .book-body .page-inner section.normal a:focus, .book .book-body .page-inner section.normal a:hover{
  background-color:  #e6ffff;
  color: darkcyan;
  border-color: darkcyan;
}

.book .book-body .page-inner section.normal a:active, .book .book-body .page-inner section.normal a:focus{
  background-color: #b3d7ff;
  color: darkblue;
  border-color: darkblue;
}

a[aria-expanded="true"], a:active[aria-expanded="true"], a:focus[aria-expanded="true"], .book .book-body .page-inner section.normal a:active[aria-expanded="true"], .book .book-body .page-inner section.normal a:focus[aria-expanded="true"]{
  background-color: #e6f2ff;
  color:   darkblue;
  border-color: darkblue;
}

.book .book-body .page-inner section.normal a {
  background-color:  #fff;
  color: #555;
  border-color: #555;
}

.open-sans-font {
  font-family: "Open Sans", sans-serif;
  font-optical-sizing: auto;
  font-weight: 500;
  font-style: normal;
  font-variation-settings:
    "wdth" 100;
}


```



```{r load-data, echo=FALSE, include=FALSE}

setwd("/Users/46079386/Library/CloudStorage/OneDrive-MacquarieUniversity/Academic/PhD/Study-1/Main Test — MTurk/Analysis/S1-MT_GLM")

load("RData/001_EDA_data.RData")

```

------------------------------------------------------------------------


# Correlations {.tabset .tabset-fade .section}

<p>Correlations were conducted using the package `correlation()`/`easy_stats`</p>

<p>Effect sizes were labelled following Funder’s (2019) recommendations.</p>

<p>The `include_factors` argument for`correlation()` is set to `TRUE`, meaning that the factors (Gender.X, childGender.X, stimuliType.X, Education.X, Ethnicity.X, Religion.X, Diet.X, IncomeBinary.X, Occupation.X) were kept and converted to a numeric value.</p>

<p>The `multilevel` argument for`correlation()` is set to `FALSE` by default, meaning that the factors were included as fixed effects in the simple regression model.</p>

<p>The `method` argument for`correlation()` is set to `"spearman"`, meaning that the variables were rank-transformed prior to estimating the correlation. This is suitable given that the data is non-parametric.</p>

```{r correlations, echo=FALSE, warning=FALSE, message=FALSE}
library(tidygraph) # plot correlations
library(ggraph)
library(see)


corr_table <- correlation(
  corr_data, # data frame for correlations
  method = "spearman", # non-parametric correlation method
  include_factors = TRUE # factors are kept and converted to numeric
)

# With regard to the stimuliType, aRobots have a high Rho on all PERVAL
# sub-scales, mRobots have a high Rho on quality PERVAL sub-scale, and
# nObject lowest on all PERVAL sub-scales

# those with a CI interval that includes 0 are:


# Group data by Paramter 1, Parameter 2, and then rho value from large to smallest

sorted_corr_table <- corr_table %>%
  dplyr::group_by(Parameter1, Parameter2, rho) %>%
  arrange(
    match(
      Parameter1, c(
        # Participant Age and Gender
        "Age", "Gender.Female", "Gender.Male",

        # Child Age and Gender
        "childAge", "childGender.Female", "childGender.Male",

        # Stimuli Type
        "stimuliType.aRobot", "stimuliType.mRobot", "stimuliType.nObject",

        # PERVAL Scale
        "socialPERVAL", "emotionPERVAL", "qualityPERVAL", "pricePERVAL",

        # IDAQ Scale
        "natureIDAQ", "technologyIDAQ", "animalIDAQ", "techNatureIDAQ",
        "overallIDAQ",

        # Stimuli Metrics (nObject)
        "nameAbility", "colourSaliency", "textureSaliency", "familiarity",

        # Stimuli Metrics (Robots)
        "HLS",

        # GAToRS
        "personalPositive", "personalNegative", "socialPositive",
        "socialNegative",

        # Demographics

        ## Religion
        "Religion.Christian", "Religion.nonChristian", "Religion.noReligion",

        ## Education
        "Education.nonHigherEducation", "Education.higherEducation",

        ## Ethnicity
        "Ethnicity.White", "Ethnicity.nonWhite",

        ## Occupation
        "Occupation.Information Technology", "Occupation.Management",
        "Occupation.Administration", "Occupation.Sales and Marketing",
        "Occupation.Healthcare", "Occupation.Other",
        "Occupation.Self Employed", "Occupation.Unemployed",

        ## Diet
        "Diet.Omnivore", "Diet.Flexitarian", "Diet.Health", "Diet.Religious",
        "Diet.Vegetarian", "Diet.Other",

        ## Income Binary
        "IncomeBinary.Upper", "IncomeBinary.Lower"
      )
    ),
#    match(
#      Parameter2,
#      c("age", "gender.Female", "gender.Male",
#        "robot_type.A", "robot_type.M",
#        "prime.A", "prime.M", "prime.C",
#        "idaq_mean", "tech_mean", "anim_mean",
#        "amoral_binom.0", "amoral_binom.1",
#        "sensibility_binom.0", "sensibility_binom.1",
#        "rigid_binom.0", "rigid_binom.1",
#        "open_binom.0", "open_binom.1",
#        "uncanny_binom.0", "uncanny_binom.1"
#      )
#    ),
    desc(rho)
  )

```

## Pairwise List {.heading}

<p>Table is organised by "Paramter1", whereby "Parameter2" is sorted and displayed from the highest correlational value (rho) with Parameter1, to lowest correlational value (rho) with Parameter1.</p>

```{r correlation list, echo=FALSE, warning=FALSE, message=FALSE}

format_cols <- c("S")

for (col in format_cols) {
  sorted_corr_table[[col]] <- format(sorted_corr_table[[col]], width = 3, scientific=TRUE)
}



sorted_corr_table %>%
  as.data.frame() %>%
  select(-Method, -n_Obs) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  # if values in `p` column is less than 0.001, replace with `< 0.001`
  mutate_at("p", ~ifelse(. < 0.001, "< 0.001", .)) %>%
  flextable() %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  bg(i = 1, bg = "white", part = "all") %>%
  bg(j = 1, bg = "white", part = "all") %>%
  set_table_properties(
    layout = "autofit",
    align = "center",
    opts_html = list(
      scroll = list(
        width = 910,
        height = 400,
        freeze_first_column = FALSE
      )
    )
  ) %>%
  theme_booktabs()

```

## Matrix {.heading}

```{r correlation-matrix, echo=FALSE, warning=FALSE, message=FALSE}

corr_table %>%
  summary() %>%
  as.data.frame() %>%
  mutate_if(is.numeric, ~round(., 3)) %>%
  flextable() %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  bg(i = 1, bg = "white", part = "all") %>%
  bg(j = 1, bg = "white", part = "all") %>%
  set_table_properties(
    layout = "autofit",
    align = "center",
    opts_html = list(
      scroll = list(
        width = 910,
        height = 400,
        freeze_first_column = TRUE
      )
    )
  ) %>%
  theme_booktabs()

```

## Plot {.heading}

### Factors Plot (CramerV) {.sub-heading}

```{r factor-correlation-plot, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=12}

# Factor Plot

factor_corr <- corr_data %>%
  select(
    Gender, Education, Ethnicity,
    Religion, Occupation, Diet,
    IncomeBinary, childGender
  )

corrplot::corrplot(DescTools::PairApply(factor_corr, DescTools::CramerV))

# Factor Level Plot

dummy_factor_corr <- factor_corr %>%
  fastDummies::dummy_cols(remove_selected_columns = TRUE)

corrplot::corrplot(DescTools::PairApply(dummy_factor_corr, DescTools::CramerV))



```

### Levels Plot (Spearman) {.heading}

```{r level-plot, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=12}


# Extract the correlation coefficients and p-values
corr_coef <- sorted_corr_table$rho
p_values <- sorted_corr_table$p

# Create a new data frame with the correlation coefficients and p-values
sorted_corr_df <- data.frame(Parameter1 = sorted_corr_table$Parameter1,
                      Parameter2 = sorted_corr_table$Parameter2,
                      Correlation = corr_coef,
                      p_value = p_values)

# Plot the correlation table using ggplot

ggplot(sorted_corr_df, aes(x = Parameter1, y = Parameter2, fill = Correlation)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


------------------------------------------------------------------------

```{r save-r-data, echo=FALSE, include=FALSE, eval=FALSE}
setwd("/Users/46079386/Library/CloudStorage/OneDrive-MacquarieUniversity/Academic/PhD/Study-1/Main Test — MTurk/Analysis/S1-MT_GLM")

save(corr_data, corr_df, factor_corr, sorted_corr_df, sorted_corr_table, file = "RData/002_correlations_data.RData")

```