```{r loadPackage}
# library(imager) # use imresize and grayscale
library(magick) # alternative to imager
library(EBImage) # can scale by one dimension, unlike imager
```

```{r loadFiles, echo=FALSE}
# set wd
setwd("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat")

# load images
filenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/scaled-images", pattern="*.jpg", full.names = TRUE)

mfilenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/magick-greyscaled-images", pattern="*.jpg", full.names = TRUE)


```

```{r editImages-imager, include=FALSE}

if (!is.null(filenames)) {
  for (idx in filenames) {
    im <- idx
    print(im)
    loaded_image <- load.image(im)

    im1 <- grayscale(loaded_image)
    im2 <- imresize(im1, scale = 0.8, interpolation = 6)
    im3 <- clean(im2)
    save.image(im = im3, file.path(dirname(im), paste0("gs_", basename(im))))
  }
}

if (!is.null(filenames)) {
  for (idx in filenames) {
    im <- idx
    print(im)
    loaded_image <- load.image(im)

    im1 <- grayscale(loaded_image)
    im2 <- resize(im1, size_x = 350, interpolation_type = 6L)
    im3 <- clean(im2)
    save.image(im = im3, file.path(dirname(im), paste0("gs350x_", basename(im))))
  }
}

```

```{r editImages-magick, include=TRUE}

# greyscale

mgsfilenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/images", pattern="*.jpg", full.names = TRUE)


if (!is.null(mgsfilenames)) {
  for (idx in mgsfilenames) {
    mim <- idx
    print(mim)
    loaded_image <- image_read(mim)

    mim1 <- loaded_image
    mim2 <- image_resize(mim1, geometry_size_pixels(height = 300))
    mim3 <- image_convert(mim2, type = "grayscale", antialias = TRUE)
    image_write(mim3, path = file.path(dirname(mim), paste0("gs_", basename(mim))))
  }
}

# scale, full colour

msfilenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/magick-scaled-images", pattern="*.jpg", full.names = TRUE)


if (!is.null(msfilenames)) {
  for (idx in msfilenames) {
    mim <- idx
    print(mim)
    loaded_image <- image_read(mim)

    mim1 <- loaded_image
    mim2 <- image_resize(mim1, geometry_size_pixels(height = 300))
    mim3 <- image_convert(mim2, antialias = TRUE)
    image_write(mim3, path = file.path(dirname(mim), paste0("magick-s_", basename(mim))))
  }
}
```

```{r editImages-EBImage, include=TRUE}

ebigsfilenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/ebi-greyscaled-images", pattern="*.jpg", full.names = TRUE)

# greyscale
if (!is.null(ebigsfilenames)) {
  for (idx in ebigsfilenames) {
    im <- idx
    print(im)
    loaded_image <- load.image(im)

    im1 <- grayscale(loaded_image)
    im2 <- resize(im1, h = 350, antialias = TRUE)
    save.image(im = im2, file.path(dirname(im), paste0("gs_", basename(im))))
  }
}

# scale, full colour


ebisfilenames <- list.files("/Users/46079386/Documents/GitHub/whoisjno.github.io/qualtrics-iat/ebi-scaled-images", pattern="*.jpg", full.names = TRUE)

if (!is.null(ebisfilenames)) {
  for (idx in ebisfilenames) {
    im <- idx
    print(im)
    loaded_image <- load.image(im)

    im1 <- loaded_image
    im2 <- resize(im1, h = 350, antialias = TRUE)
    save.image(im = im2, file.path(dirname(im), paste0("s_", basename(im))))
  }
}
```

